POSITION = "Position"
EXACT_POSITION = "ExactPosition"
REGION = "Region"
LIST_OF_REGIONS = "ListOfRegions"
INBETWEEN_POSITION = "InBetweenPosition"
FUZZY_POSITION = "FuzzyPosition"
INRANGE_POSITION = "InRangePosition"
NEGATIVE_STRAND = "NegativeStrand"