PREFIX dcterm: <http://purl.org/dc/terms/>
PREFIX oa: <http://www.w3.org/ns/oa#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?geneId (count(?ref) as ?refCount)
WHERE {
  graph <http://rdfportal.org/dataset/pubtator_central> {
  [ a oa:Annotation ;
  oa:hasBody ?geneId ;
  oa:hasTarget ?ref ;
  dcterm:subject "Gene" ].
  VALUES ?geneId {
    <http://identifiers.org/ncbigene/$ncbigene>
  }
}}
GROUP BY ?geneId